version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: "12:00"
    cooldown:
      default-days: 3
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: "12:00"
    cooldown:
      default-days: 3
    allow:
      - dependency-type: all
    groups:
      all:
        patterns:
          - "*"
