services:
  db-init:
    build:
      context: .
      target: db-init
    environment:
      LUMI_STATIC_DB_DIR: /app/run/static
      LUMI_STATE_DB_DIR: /app/run/state
    volumes:
      - db-static:/app/run/static
      - ./run/state:/app/run/state

  bot:
    image: "ghcr.io/dawnbrandbots/lumi-bot:${DOCKER_TAG:-latest}"
    environment:
      DEBUG: "*"
      DISCORD_TOKEN:
      LUMI_STATIC_DB_DIR: /app/run/static
      LUMI_STATE_DB_DIR: /app/run/state
    logging:
      driver: "${DOCKER_LOG_DRIVER:-journald}"
    build:
      context: .
      target: bot
    depends_on:
      db-init:
        condition: service_completed_successfully
    restart: unless-stopped
    volumes:
      - db-static:/app/run/static:ro
      - ./run/state:/app/run/state

volumes:
  db-static:
