services:
  db-init:
    build:
      context: .
      target: db-init
    volumes:
      - db-static:${LUMI_STATIC_DB_DIR}
      - ${LUMI_STATE_DB_HOST_DIR}:${LUMI_STATE_DB_DIR}

  bot:
    image: "ghcr.io/dawnbrandbots/lumi-bot:${DOCKER_TAG:-latest}"
    environment:
      DEBUG: ${DEBUG}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
    logging:
      driver: "${DOCKER_LOG_DRIVER:-journald}"
    build:
      context: .
      target: bot
    depends_on:
      db-init:
        condition: service_completed_successfully
    restart: unless-stopped
    volumes:
      - db-static:${LUMI_STATIC_DB_DIR:-/app/run/static}:ro
      - ${LUMI_STATE_DB_HOST_DIR}:${LUMI_STATE_DB_DIR}

volumes:
  db-static:
