name: Deploy

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      revision:
        description: "GitHub commit SHA"
        required: false
        default: ""

env:
  # docker/metadata-action type=sha,format=long
  DOCKER_TAG: sha-${{ github.event.inputs.revision || github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Lumi#0961
    steps:
      - uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:github-actions
          version: latest
          # ping doesn't seem to be working but does not impact connectivity
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.inputs.revision || github.sha }}
      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy with Docker Compose
        env:
          DOCKER_HOST: tcp://${{ secrets.TS_DEPLOY_HOST }}:${{ secrets.TS_DEPLOY_PORT }}
          DOCKER_TAG: ${{ env.DOCKER_TAG }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: |
          docker compose pull
          docker compose up -d
      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: yarn
      - run: yarn
      - name: Deploy Slash Commands
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: |
          yarn register
          yarn register user-install
      - name: Update bot profile
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: |
          yarn bot:profile:update
