name: Compile and lint

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [ready_for_review, review_requested]

permissions: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: yarn
      - run: yarn
      - run: yarn typecheck
      - run: yarn lint
      - run: cp .env.test.template .env.test && yarn test
      - run: yarn format:check
      - run: cp .env.test.template .env.test && yarn test
